name: 'discord-send-embed'
description: 'discord-send-embed is a github composite action to send embed messages using discord channels webhook URL.'
inputs:
  webhook-url:
    description: 'Discord webhook URL'
    required: true
    default: ''
  title:
    description: 'Title of the embed message'
    required: false
    default: ''
  url:
    description: 'Title URL of the embed message'
    required: false
    default: ''
  description:
    description: 'Descrition of the embed message'
    required: true
    default: ''
  color:
    description: 'Decimal color code (Convert HEX to DECIMAL)'
    required: false
    default: 65280
  footer-text:
    description: 'Footer text'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Discord Send Embed Message
      shell: bash
      run: |
        DESCRIPTION=$(echo "${{ inputs.description }}" | tr -d '\n')
        curl -X POST -H "Content-Type: application/json" \
        -d '{
          "embeds": [
            {
              "title": "${{ inputs.title }}",
              "url": "${{ inputs.url }}",
              "description": "'"$DESCRIPTION"'",
              "color": '"${{ inputs.color }}"',
              "footer": {
                "text": "${{ inputs.footer-text }}"
              }
            }
          ]
        }' \
        "${{ inputs.webhook-url }}"

